name: Build docker image

on:
  release:
    types: [created]

jobs:
  Build_Docker_Image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      run: docker build -t ghcr.io/hei-synd-225-sem/sdi-tdd-lab:latest .

    - name: Push docker image
      run: docker push ghcr.io/hei-synd-225-sem/sdi-tdd-lab:latest

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: .
